version: '3.8'
services:
  database:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: assettacker
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
      args:
        - PORT=8080
    ports:
      - 8080:8080
    environment:
      - API_URL="${API_URL}:${API_PORT}"
    depends_on:
      - database
      - backend
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
      args:
        - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - database
