version: "3.8"
services:
  database:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: assettracker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "assettracker"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    environment:
      - VUE_APP_API_URL=http://${API_URL}:${API_PORT}
    depends_on:
      - database
      - backend
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - PORT=3000
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      database:
        condition: service_healthy
